### ISSUE TITLE
Idea to get the animations under the appbar

### ISSUE THREAD

**Issue by MaskyS** [BigMarco254/FlutterTodo#1]
I think you can get the size of the appbar from this https://stackoverflow.com/questions/50075945/appbar-height-in-flutter and then adjust your animation accordingly? :D

**Comment by MarcL01** [comment]
The issue is I don't know if there is any way to adjust Hero while it is in movement. So instead I'm looking for a function that is called when the Hero's are done animating then I could just do my animations after that call.
