### ISSUE TITLE
Not compatible with Dart Version >2.00.00

### ISSUE THREAD

**Issue by BishwajitNepali** [BigMarco254/FlutterTodo#3]
This is not compatible with Dart Version >2.00.00 .

**Comment by Ufuk94** [comment]
> This is not compatible with Dart Version >2.00.00 .

Open pubspec.yaml and change the version numbers for uuid and intl to "any"
<img width="396" alt="yaml" src="https://user-images.githubusercontent.com/19354637/52973678-1ffdaf00-33bf-11e9-96f8-ad066986b0cd.png">

**Comment by MarcL01** [comment]
Addressed in https://github.com/littlemarc2011/FlutterTodo/commit/40c94f204554ad27335faea6589b23cfdfb3f1cd
